name: smartlocker
description: A modern e-commerce UI application in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Packages
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0 # For placeholder charts
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Definisikan folder assets Anda di sini
  assets:
    - assets/images/
    - assets/icons/